"""
Explainable AI (XAI) Formatter for CyberShield AI.

Purpose:
    Converts structured analysis dictionaries (produced by the response parser)
    into consistent, professional XAI markdown reports that are short, clear
    and easy for everyday users to understand.

    The layout mirrors the classic CyberShield report style described in the
    original `gemini_service.py`:

        Website / Image :  ### 🛡️ Explainable AI (XAI) Assessment:
        Email           :  ### 📧 Security Assessment: <risk_level>
        Password        :  ### 🔑 Strength Report: <risk_level>
        Advisor         :  ### 🛡️ Cyber Shield Security Advisor Summary

    Each report uses 2-5 short scannable bullet points with bold labels, and
    image reports include a short plain-language "Visual Analysis Details"
    paragraph. This produces clean, commercial-product output instead of a
    generic chatbot monologue.

Public methods:
    format_report(data, analysis_type)          -> str  (auto-dispatch)
    format_website_report(data)                 -> str
    format_email_report(data)                   -> str
    format_image_report(data)                   -> str
    format_password_report(data)                -> str
    format_advisor_report(data)                 -> str
    format_generic_report(data)                 -> str  (fallback)
"""

from typing import Any, Dict, List, Optional

from utils.logger import get_logger

logger = get_logger(__name__)


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------

def _safe_str(value: Any, default: str = "N/A") -> str:
    """Returns a safe string representation of a value."""
    if value is None:
        return default
    if isinstance(value, bool):
        return "Yes" if value else "No"
    if isinstance(value, float):
        return f"{value:.2f}"
    return str(value)


def _safe_list(value: Any) -> List[str]:
    """Ensures the value is a list of strings."""
    if not value:
        return []
    if isinstance(value, list):
        return [str(item) for item in value if item]
    if isinstance(value, str):
        return [value]
    return [str(value)]


def _bullet(items: Optional[List[str]], default: str = "No data available.") -> str:
    """Formats a list of strings as simple markdown bullets."""
    items = _safe_list(items)
    if not items:
        return f"* {default}\n"
    return "".join(f"* {item}\n" for item in items)


def _kv_bullets(pairs: Dict[str, Any]) -> str:
    """Formats key/value pairs as classic bold-label bullets: '* **Label**: value'."""
    if not pairs:
        return "* No data available.\n"
    return "\n".join(
        f"* **{key.replace('_', ' ').title()}**: {_safe_str(value)}"
        for key, value in pairs.items()
    ) + "\n"


# ---------------------------------------------------------------------------
# Module-specific formatters
# ---------------------------------------------------------------------------

def format_website_report(data: Dict[str, Any]) -> str:
    """
    Builds a classic short XAI report for website / URL analysis.
    """
    risk_level = _safe_str(data.get("risk_level"), "Unknown")
    summary = _safe_str(data.get("summary"), "No summary available.")
    reasoning = _safe_list(data.get("reasoning"))
    recommendations = _safe_list(data.get("recommendations"))
    limitations = _safe_list(data.get("limitations"))

    malware_found = data.get("malware_found")
    malware_label = "No malware signatures flagged" if not malware_found else "Malware indicators detected"

    report = "### 🛡️ Explainable AI (XAI) Assessment:\n\n"
    report += f"* **Risk Level**: {risk_level}.\n"
    report += f"* **Malware Detection**: {malware_label}.\n\n"

    if reasoning:
        report += "**Why This Assessment:**\n" + _bullet(reasoning) + "\n"

    report += "**Recommendation:**\n" + _bullet(recommendations, "No specific recommendation available.") + "\n"

    if limitations:
        report += "**Limitations:**\n" + _bullet(limitations) + "\n"

    if summary and summary != "No summary available.":
        report += f"*Summary: {summary}*\n"

    report += "\n_Report generated by CyberShield AI Explainable Analysis Engine._\n"
    return report


def format_email_report(data: Dict[str, Any]) -> str:
    """
    Builds a classic short XAI report for email phishing analysis.

    Header: ### 📧 Security Assessment: <risk_level>
    """
    risk_level = _safe_str(data.get("risk_level"), "Unknown")
    confidence = _safe_str(data.get("confidence"), "0")
    summary = _safe_str(data.get("summary"), "No summary available.")
    reasoning = _safe_list(data.get("reasoning"))
    recommendations = _safe_list(data.get("recommendations"))
    limitations = _safe_list(data.get("limitations"))

    spoofed = data.get("spoofed_domain")
    spoof_label = "Sender address does not match the legitimate brand domain" if spoofed else "No domain spoofing detected"
    phishing_score = data.get("phishing_score")

    report = f"### 📧 Security Assessment: {risk_level}\n\n"
    report += f"* **Phishing Score**: {_safe_str(phishing_score) if phishing_score is not None else 'N/A'}% — probability of fraudulent mail.\n"
    report += f"* **Spoofing Check**: {spoof_label}.\n"
    report += f"* **Urgency Language**: {_safe_str(data.get('urgency'), 'Normal')} urgency signals detected in the message body.\n"
    report += f"* **Social Engineering**: {_safe_str(data.get('social_engineering'), 'Not Assessed')}.\n"
    report += f"* **Suspicious Links**: {_safe_str(data.get('suspicious_links'), '0')} hyperlink reference(s) found in the content.\n"
    report += f"* **SPF Check**: {_safe_str(data.get('spf_check'), 'Not Available')}; DKIM: {_safe_str(data.get('dkim_check'), 'Not Available')}; DMARC: {_safe_str(data.get('dmarc_check'), 'Not Available')}.\n\n"

    if reasoning:
        report += "**Why This Assessment:**\n" + _bullet(reasoning) + "\n"

    report += "**Recommendation:**\n" + _bullet(recommendations, "No specific recommendation available.") + "\n"

    if limitations:
        report += "**Limitations:**\n" + _bullet(limitations) + "\n"

    if summary and summary != "No summary available.":
        report += f"*Summary: {summary}*\n"

    report += "\n_Report generated by CyberShield AI Explainable Analysis Engine._\n"
    return report


def format_image_report(data: Dict[str, Any]) -> str:
    """
    Builds a classic short XAI report for image authenticity analysis.

    Header: ### 🛡️ Explainable AI (XAI) Assessment:
    Then 2-3 short bullets + a "Visual Analysis Details" paragraph.
    """
    risk_level = _safe_str(data.get("risk_level"), "Unknown")
    confidence = _safe_str(data.get("confidence"), "0")
    summary = _safe_str(data.get("summary"), "No summary available.")
    reasoning = _safe_list(data.get("reasoning"))
    recommendations = _safe_list(data.get("recommendations"))
    limitations = _safe_list(data.get("limitations"))

    ai_prob = data.get("ai_probability", data.get("ai_confidence"))
    ai_prob_label = f"{_safe_str(ai_prob)}%" if ai_prob is not None else "N/A"

    report = "### 🛡️ Explainable AI (XAI) Assessment:\n\n"
    report += f"* **Risk Classification**: {risk_level} (confidence {confidence}%).\n"
    report += f"* **AI Probability**: {ai_prob_label} chance the image is AI-generated or digitally manipulated.\n"

    # Short forensic clues (2-3 bullets).
    forensic_clues = []
    if reasoning:
        forensic_clues = reasoning[:3]
    elif data.get("gan_artifacts"):
        forensic_clues.append(f"GAN Artifacts: {data.get('gan_artifacts')}.")
    if data.get("noise") or data.get("noise_score"):
        forensic_clues.append(f"Noise Analysis: {_safe_str(data.get('noise') or data.get('noise_score'))}.")
    if data.get("lighting_consistency") or data.get("lighting"):
        forensic_clues.append(f"Lighting Consistency: {_safe_str(data.get('lighting_consistency') or data.get('lighting'))}.")
    if data.get("pixel_irregularity"):
        forensic_clues.append(f"Pixel Irregularity: {data.get('pixel_irregularity')}.")
    if data.get("compression_analysis"):
        forensic_clues.append(f"Compression Analysis: {data.get('compression_analysis')}.")

    if forensic_clues:
        for clue in forensic_clues[:3]:
            report += f"* **Forensic Clue**: {clue}\n"
    report += "\n"

    # Plain-language visual analysis paragraph (classic style).
    if risk_level.lower() in ("unsafe", "malicious", "suspicious", "fake", "ai-generated"):
        verdict_desc = "synthetic generation or digital manipulation"
    else:
        verdict_desc = "authentic, natural photography"

    report += "**Visual Analysis Details:**\n"
    if summary and summary != "No summary available.":
        report += f"{summary} "
    report += (
        f"The forensic evidence points toward {verdict_desc}. "
        "Generative models and editing tools commonly leave detectable traces in "
        "noise distribution, lighting coherence, and edge/texture micro-patterns. "
        "Review the specific indicators above before making a final determination.\n\n"
    )

    report += "**Recommendation:**\n" + _bullet(recommendations, "No specific recommendation available.") + "\n"

    if limitations:
        report += "**Limitations:**\n" + _bullet(limitations) + "\n"

    report += "\n_Report generated by CyberShield AI Explainable Forensic Engine._\n"
    return report


def format_password_report(data: Dict[str, Any]) -> str:
    """
    Builds a classic short XAI report for password strength analysis.

    Header: ### 🔑 Strength Report: <risk_level>
    """
    risk_level = _safe_str(data.get("risk_level"), "Unknown")
    confidence = _safe_str(data.get("confidence"), "0")
    summary = _safe_str(data.get("summary"), "No summary available.")
    reasoning = _safe_list(data.get("reasoning"))
    recommendations = _safe_list(data.get("recommendations"))
    limitations = _safe_list(data.get("limitations"))

    pwned = data.get("pwned_count", 0)
    breach_label = (
        f"⚠️ Flagged {pwned} time(s) in known breach databases" if pwned and pwned > 0
        else "✅ No immediate breach records matching this profile"
    )
    entropy = data.get("entropy")

    report = f"### 🔑 Strength Report: {risk_level}\n\n"
    if entropy is not None:
        report += f"* **Entropy Rating**: **{_safe_str(entropy)} bits** — passwords should ideally exceed 60 bits to resist GPU brute force.\n"
    report += f"* **Length Check**: Found {_safe_str(data.get('length'))} characters; optimal length is 16+ characters.\n"
    report += f"* **Breach Database**: {breach_label}.\n"
    report += f"* **Dictionary Risk**: {_safe_str(data.get('dictionary_risk'), 'Not Assessed')}.\n"
    report += f"* **Pattern Detection**: {_safe_str(data.get('pattern_detection'), 'None Detected')}.\n"
    report += f"* **Estimated Crack Time**: {_safe_str(data.get('estimated_crack_time'), 'N/A')}.\n"
    report += (
        "* **Character Variety**: "
        f"Uppercase {'✓' if data.get('has_uppercase') else '✗'} | "
        f"Lowercase {'✓' if data.get('has_lowercase') else '✗'} | "
        f"Digits {'✓' if data.get('has_digit') else '✗'} | "
        f"Symbols {'✓' if data.get('has_special') else '✗'}.\n\n"
    )

    if reasoning:
        report += "**Why This Assessment:**\n" + _bullet(reasoning) + "\n"

    report += "**Action Steps:**\n" + _bullet(recommendations, "No specific recommendation available.") + "\n"

    if limitations:
        report += "**Limitations:**\n" + _bullet(limitations) + "\n"

    if summary and summary != "No summary available.":
        report += f"*Summary: {summary}*\n"

    report += "\n_Report generated by CyberShield AI Explainable Analysis Engine._\n"
    return report


def format_advisor_report(data: Dict[str, Any]) -> str:
    """
    Builds a classic short XAI report for the security posture advisor.

    Header: ### 🛡️ Cyber Shield Security Advisor Summary
    Includes health score, key profile statistics, and immediate action items.
    """
    risk_level = _safe_str(data.get("risk_level"), "Unknown")
    overall_score = data.get("overall_score", "N/A")
    summary = _safe_str(data.get("summary"), "No summary available.")
    reasoning = _safe_list(data.get("reasoning"))
    limitations = _safe_list(data.get("limitations"))

    report = "### 🛡️ Cyber Shield Security Advisor Summary\n\n"
    report += f"Based on your profile, your Cyber Security Health Score is **{_safe_str(overall_score)}/100** "
    report += f"(overall risk: **{risk_level}**).\n\n"

    if summary and summary != "No summary available.":
        report += f"{summary}\n\n"

    raw_recs = data.get("recommendations", [])

    # Structured recommendation objects (title / priority / action_steps / reason).
    if raw_recs and isinstance(raw_recs[0], dict):
        report += "#### 🚩 Immediate Action Items:\n\n"
        for idx, rec in enumerate(raw_recs, start=1):
            title = rec.get("title", f"Priority {idx}")
            priority = rec.get("priority", "Medium")
            category = rec.get("category", "General")
            steps = rec.get("action_steps", "No steps provided.")
            reason = rec.get("reason", "")
            report += f"**{idx}. {title}** (Priority: {priority} | Category: {category})\n"
            report += f"* **Action Steps**: {steps}\n"
            if reason:
                report += f"* **Why It Helps**: {reason}\n"
            report += "\n"
    else:
        recs = _safe_list(raw_recs)
        if recs:
            report += "#### 🚩 Immediate Action Items:\n\n"
            for idx, rec in enumerate(recs[:5], start=1):
                report += f"{idx}. {rec}\n"
            report += "\n"

    if reasoning:
        report += "**Why This Assessment:**\n" + _bullet(reasoning) + "\n"

    if limitations:
        report += "**Limitations:**\n" + _bullet(limitations) + "\n"

    report += "\n_Report generated by CyberShield AI Explainable Analysis Engine._\n"
    return report


def format_generic_report(data: Dict[str, Any]) -> str:
    """
    Fallback formatter that produces a standard XAI report from any
    validated analysis dictionary.
    """
    risk_level = _safe_str(data.get("risk_level"), "Unknown")
    confidence = _safe_str(data.get("confidence"), "0")
    summary = _safe_str(data.get("summary"), "No summary available.")
    reasoning = _safe_list(data.get("reasoning"))
    recommendations = _safe_list(data.get("recommendations"))
    limitations = _safe_list(data.get("limitations"))

    report = "### 🛡️ Explainable AI (XAI) Assessment:\n\n"
    report += f"* **Risk Level**: {risk_level} (confidence {confidence}%).\n"
    report += f"* **Summary**: {summary}.\n\n"
    report += "**Why This Assessment:**\n" + _bullet(reasoning) + "\n"
    report += "**Recommendations:**\n" + _bullet(recommendations) + "\n"
    if limitations:
        report += "**Limitations:**\n" + _bullet(limitations) + "\n"
    report += "\n_Report generated by CyberShield AI Explainable Analysis Engine._\n"
    return report


# ---------------------------------------------------------------------------
# Public dispatcher
# ---------------------------------------------------------------------------

# Mapping of analysis types to their dedicated formatters.
_FORMATTERS = {
    "website": format_website_report,
    "email": format_email_report,
    "image": format_image_report,
    "password": format_password_report,
    "advisor": format_advisor_report,
}


def format_report(data: Dict[str, Any], analysis_type: Optional[str] = None) -> str:
    """
    Converts a structured analysis dictionary into a clean, professional
    XAI markdown report.

    Auto-dispatches to the module-specific formatter based on
    analysis_type. Falls back to the generic formatter if no match.

    If the data already contains an 'explanation_markdown' field, it is
    preserved as a fallback — but the formatter's output takes priority
    to ensure consistency.

    Args:
        data: The validated analysis dictionary from the response parser.
        analysis_type: Optional override for the analysis type.
            If not provided, the value of data['analysis_type'] is used.

    Returns:
        A markdown-formatted XAI report string.
    """
    if not data or not isinstance(data, dict):
        logger.warning("XAI formatter received invalid data; returning fallback.")
        return format_generic_report({})

    # Determine the analysis type.
    atype = (analysis_type or data.get("analysis_type") or "").lower().strip()

    formatter = _FORMATTERS.get(atype)
    if formatter:
        try:
            return formatter(data)
        except Exception as exc:
            logger.error("XAI formatter error for type '%s': %s", atype, exc)
            return format_generic_report(data)

    return format_generic_report(data)

